# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

repos:
- repo: https://git.afpy.org/AFPy/powrap
  # there's no release tag in repo, use the latest commit hash id instead
  rev: v1.0.2
  hooks:
  - id: powrap