# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

repos:
- repo: https://git.afpy.org/AFPy/powrap
  # there's no release tag in repo, use the latest commit hash id instead
  rev: a34a9fed116d24562fbe4bb8d456ade85f056c36
  hooks:
  - id: powrap