body:
  - type: markdown
    attributes:
      value: |
        感謝你參與本翻譯計畫 🚀

        謝謝你願意補充術語，讓志工們的翻譯流程更順暢 🙏

        接下來請麻煩依照下列的步驟完成術語補充，我們將在下一次的 meetup 討論新增的術語，並整理至術語表當中。

  - type: checkboxes
    id: steps_check
    attributes:
      label: 初步確認
      description: 請確認下列每個步驟都已經完成。
      options:
        - label: 我已經確認過 [術語列表](https://github.com/python/python-docs-zh-tw/wiki/%E8%A1%93%E8%AA%9E%E5%88%97%E8%A1%A8) 中沒有相關術語。
          required: true
        - label: 我已經確認過 [Python 官方術語列表](https://docs.python.org/zh-tw/3/glossary.html) 中沒有相關術語。
          required: true

  - type: input
    id: term_eng
    attributes:
      label: 術語原文
    validations:
      required: true

  - type: input
    id: term_zh
    attributes:
      label: 術語翻譯
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 說明
      description: |
        請補充說明原文出處和想新增詞彙的原因。

    validations:
      required: true


  - type: textarea
    id: reference
    attributes:
      label: 參考資料
      description: 若有其他參考資料，也請麻煩附上，可以加速 reviewer 的作業流程喔。