name: deploy-gh-page

on:
  push:
    branches:
      - "3.14"

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: sudo apt-get install gettext

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build
        run: JOBS=4 MODE=html make all

      - name: Deploy to gh page
        uses: JamesIves/github-pages-deploy-action@v4.7.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ../cpython/Doc/build/html
          clean: true
          clean-exclude: pr-preview/
